### ISSUE TITLE
Feat: [Docker] 통신 환경 구축 - Docker Compose (networks)

### ISSUE THREAD

**Issue by 66yurimi99** [66yurimi99/Z-ERO#8]
## Description  
컨테이너 간 통신을 위해 `compose.yaml` 파일에서 네트워크 환경 bridge을 설정합니다.
<br>

## 요구사항
Host PC (Ubuntu)와 Docker 컨테이너 간의 원활한 통신을 위해 네트워크를 정의합니다. 
```yaml
networks: 
  mynetwork: 
  driver: bridge
```
<br>

## 산출물
- [ ] `compose.yaml`
